main: com.gmail.St3venAU.plugins.ArmorStandTools.Main
name: ArmorStandTools
version: "${version}"
api-version: 1.15
authors: [St3venAU, NotMyFault]
description: Armor stand manipulation tools
softdepend: [WorldGuard, PlotSquared]
commands:
   astools:
      description: Give yourself the armor stand tools
      aliases: ast
      usage: Usage /astools or /astools reload
   ascmd:
      description: View/Remove/Assign the command assigned to the nearest armor stand
      usage: Usage /ascmd view, /ascmd remove, /ascmd assign <player/console> <command>